/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PhysicalIdRouteImport } from './routes/physical.$id'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as ApiAstroApertureGraphqlRouteImport } from './routes/api/astro-aperture/graphql'
import { Route as ApiAstroApertureImageRouteImport } from './routes/api/astro-aperture/image'
import { Route as ApiNavigatorSplatRouteImport } from './routes/api/navigator.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalIdRoute = PhysicalIdRouteImport.update({
  id: '/physical/$id',
  path: '/physical/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAstroApertureGraphqlRoute = ApiAstroApertureGraphqlRouteImport.update({
  id: '/api/astro-aperture/graphql',
  path: '/api/astro-aperture/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAstroApertureImageRoute = ApiAstroApertureImageRouteImport.update({
  id: '/api/astro-aperture/image',
  path: '/api/astro-aperture/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNavigatorSplatRoute = ApiNavigatorSplatRouteImport.update({
  id: '/api/navigator/$',
  path: '/api/navigator/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/gallery': typeof GalleryRoute
  '/studio': typeof StudioRoute
  '/physical/$id': typeof PhysicalIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/astro-aperture/graphql': typeof ApiAstroApertureGraphqlRoute
  '/api/astro-aperture/image': typeof ApiAstroApertureImageRoute
  '/api/navigator/$': typeof ApiNavigatorSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/gallery': typeof GalleryRoute
  '/studio': typeof StudioRoute
  '/physical/$id': typeof PhysicalIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/astro-aperture/graphql': typeof ApiAstroApertureGraphqlRoute
  '/api/astro-aperture/image': typeof ApiAstroApertureImageRoute
  '/api/navigator/$': typeof ApiNavigatorSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/gallery': typeof GalleryRoute
  '/studio': typeof StudioRoute
  '/physical/$id': typeof PhysicalIdRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/astro-aperture/graphql': typeof ApiAstroApertureGraphqlRoute
  '/api/astro-aperture/image': typeof ApiAstroApertureImageRoute
  '/api/navigator/$': typeof ApiNavigatorSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/gallery'
    | '/studio'
    | '/physical/$id'
    | '/project/$id'
    | '/api/astro-aperture/graphql'
    | '/api/astro-aperture/image'
    | '/api/navigator/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/gallery'
    | '/studio'
    | '/physical/$id'
    | '/project/$id'
    | '/api/astro-aperture/graphql'
    | '/api/astro-aperture/image'
    | '/api/navigator/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/gallery'
    | '/studio'
    | '/physical/$id'
    | '/project/$id'
    | '/api/astro-aperture/graphql'
    | '/api/astro-aperture/image'
    | '/api/navigator/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  GalleryRoute: typeof GalleryRoute
  StudioRoute: typeof StudioRoute
  PhysicalIdRoute: typeof PhysicalIdRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ApiAstroApertureGraphqlRoute: typeof ApiAstroApertureGraphqlRoute
  ApiAstroApertureImageRoute: typeof ApiAstroApertureImageRoute
  ApiNavigatorSplatRoute: typeof ApiNavigatorSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical/$id': {
      id: '/physical/$id'
      path: '/physical/$id'
      fullPath: '/physical/$id'
      preLoaderRoute: typeof PhysicalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/astro-aperture/graphql': {
      id: '/api/astro-aperture/graphql'
      path: '/api/astro-aperture/graphql'
      fullPath: '/api/astro-aperture/graphql'
      preLoaderRoute: typeof ApiAstroApertureGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/astro-aperture/image': {
      id: '/api/astro-aperture/image'
      path: '/api/astro-aperture/image'
      fullPath: '/api/astro-aperture/image'
      preLoaderRoute: typeof ApiAstroApertureImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/navigator/$': {
      id: '/api/navigator/$'
      path: '/api/navigator/$'
      fullPath: '/api/navigator/$'
      preLoaderRoute: typeof ApiNavigatorSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  GalleryRoute: GalleryRoute,
  StudioRoute: StudioRoute,
  PhysicalIdRoute: PhysicalIdRoute,
  ProjectIdRoute: ProjectIdRoute,
  ApiAstroApertureGraphqlRoute: ApiAstroApertureGraphqlRoute,
  ApiAstroApertureImageRoute: ApiAstroApertureImageRoute,
  ApiNavigatorSplatRoute: ApiNavigatorSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
